name: Send Daily Email

on:
  schedule:
    # 定时每天运行一次，时间为 UTC 时间
    - cron: '50 23 * * *' # 每天 23:50 (UTC 时间) 运行（北京时间07:50）

  workflow_dispatch: # 手动触发支持

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: 设置 Node.js 运行环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # 使用 Node.js 14

      # Step 3: 安装依赖
      - name: Install Dependencies
        run: npm install

      # Step 4: 执行发送邮件脚本
      - name: Run Email Script
        run: node index.js
